#!/usr/bin/env python3
"""
gen_inventory.py — render docs/sources/INVENTORY.md from docs/sources/sources.yaml.

INVENTORY.md is auto-generated. Edit sources.yaml and re-run this script;
do not hand-edit INVENTORY.md.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit(
        "gen_inventory: pyyaml is not installed.\n"
        "hint: run `python tasks.py install` first."
    )

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "sources" / "sources.yaml"
OUT = ROOT / "docs" / "sources" / "INVENTORY.md"

KIND_ORDER = ["rulebook", "enforcement-rule", "tour-page", "notice", "press-release"]
KIND_LABELS = {
    "rulebook": "Rulebooks",
    "enforcement-rule": "Enforcement Rules",
    "tour-page": "Tour Pages (KRX overview content)",
    "notice": "Notices",
    "press-release": "Press Releases",
}

MARKETS_ORDER = ["KOSPI", "KOSDAQ"]


def _markets_label(markets: list[str]) -> str:
    if set(markets) == {"KOSPI", "KOSDAQ"}:
        return "KOSPI + KOSDAQ"
    return ", ".join(markets) if markets else "—"


def _markets_key(markets: list[str]) -> tuple:
    """Sort key: KOSPI-only first, then KOSDAQ-only, then both."""
    s = set(markets)
    if s == {"KOSPI"}:
        return (0,)
    if s == {"KOSDAQ"}:
        return (1,)
    return (2,)


def _topics_str(topics: list[str]) -> str:
    return ", ".join(topics) if topics else "—"


def _row(src: dict) -> str:
    auth = "yes" if src.get("authoritative") else "—"
    return (
        f"| `{src['id']}` "
        f"| {src['title']} "
        f"| {_markets_label(src.get('markets', []))} "
        f"| {_topics_str(src.get('topics', []))} "
        f"| {src.get('language', '?')} "
        f"| {auth} "
        f"| {src.get('fetched', '—')} "
        f"| [archive](./{src['archive']}) "
        f"| [src]({src['url']}) |"
    )


def _section_header() -> str:
    return (
        "| ID | Title | Markets | Topics | Lang | Auth | Fetched | Archive | URL |\n"
        "|---|---|---|---|---|---|---|---|---|"
    )


def render(data: dict) -> str:
    sources = data.get("sources", []) or []
    by_kind: dict[str, list[dict]] = {}
    for s in sources:
        by_kind.setdefault(s.get("kind", "unknown"), []).append(s)

    lines: list[str] = []
    lines.append("# Source Inventory")
    lines.append("")
    lines.append(
        "> **Auto-generated** from `sources.yaml` by `tools/gen_inventory.py`. "
        "Do not edit this file directly — edit `sources.yaml` and re-run "
        "`python tasks.py gen-inventory`."
    )
    lines.append("")
    lines.append(f"_Generated: {date.today().isoformat()}_")
    lines.append("")
    lines.append(f"**Total sources tracked:** {len(sources)}")
    lines.append("")
    lines.append("## How to use this index")
    lines.append("")
    lines.append(
        "Cite a source by its `ID` from the tables below. In topic Markdown frontmatter:"
    )
    lines.append("")
    lines.append("```yaml")
    lines.append("sources:")
    lines.append("  - KRX-TOUR-KOSPI-OPS-T2")
    lines.append("  - KRX-TOUR-KOSPI-OPS-T9")
    lines.append("```")
    lines.append("")
    lines.append("Inline citation in prose: `[KRX-TOUR-KOSPI-OPS-T2 §3]`. See `docs/STYLE.md` §5.")
    lines.append("")

    ordered_kinds = [k for k in KIND_ORDER if k in by_kind] + sorted(
        k for k in by_kind if k not in KIND_ORDER
    )
    for kind in ordered_kinds:
        entries = by_kind[kind]
        lines.append(f"## {KIND_LABELS.get(kind, kind)} ({len(entries)})")
        lines.append("")
        entries_sorted = sorted(entries, key=lambda s: (_markets_key(s.get("markets", [])), s["id"]))
        lines.append(_section_header())
        for s in entries_sorted:
            lines.append(_row(s))
        lines.append("")

    lines.append("## Schema")
    lines.append("")
    lines.append("See header comments of `sources.yaml` for the full field schema and the controlled topic-tag vocabulary.")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    if not SRC.exists():
        print(f"gen_inventory: missing {SRC}", file=sys.stderr)
        return 1
    with SRC.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)
    OUT.write_text(render(data), encoding="utf-8")
    n = len(data.get("sources", []) or [])
    print(f"gen_inventory: wrote {OUT.relative_to(ROOT)} ({n} sources).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
